# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d8l8SnnLwV77UVfbvXbXffhJyzRgcY3mNw+NKu9nNJE5drUIea9WyM52pmjI5+BTvWtgQTsRkIsYVJKTF7IXRlRR4O91hlBfAXsRZJQ6VEgIkHi2m2hIoGs+DH7TKHG1jMs3tdj0ReKedvhb2f4y/zaw+ca5NXxPm0AEsp8qOxty8lftEzjONNhhs6EG0P1yj5g+zuawl/rOPExhT8qTslCgaCctxJUOzxNp4ORnn+/Tt53g8bIJJyQ8Dfar+QUoSpKVc0DPhL6Suvy6HfIxDa9ikX1H1UVZDX5feGn7GPT2SRE0kh9a8FDHIIoDVUq9AsniALlSOv67X+TAsX5x1azDWublm7RvCAT3Fj6pp+ojZQB/jZn8FG3ckdyVJIkzel6ULFIFMj8u/KrWXU74SPTBJoV1rwXe/CpjRChUbgGPtUiskJGPj+TbG3Xd9adF7cs8wFwFKQZJgAE4B0G2eWgfOlTC9GtIVg12n9ipUbuIvU05YzQsNwbXs/LhuByueqZwsPuFAkrKWZXw62+/KOG7PX/UTDfI7c2QZCyFDvfutZElO1HBhHZYQxnAnM3YWvPXFtDnlnQ+S6mjnIDOf+jQYPdZoXOvexgpv4IaLFm8Gt+73+vrEa8g5es1/6LqgMFZOYiRGXM0/NPPHbFRlUfebkegvToly/kOXiVOmMc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe


after_failure:
  - ls -lart # where are we?
  - if [ -f /Users/travis/miniconda3/conda-bld/work/netcdf-cxx4-4.3.0/config.log ]; then cat /Users/travis/miniconda3/conda-bld/work/netcdf-cxx4-4.3.0/config.log && sleep 10; fi
  - echo == End of config.log ==

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
